from typing import Dict, List, Optional, Any
from pydantic import BaseModel, Field

from langchain_core.messages import AIMessage, HumanMessage, BaseMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder, PromptTemplate
from langchain_core.output_parsers import PydanticOutputParser

from agents.questioner.models import get_hf_llm


# Output schema for questions generated by the counselor agent
class QuestionMessage(BaseModel):
    ai: str = Field(description="The cognitive evaluation question asked by the counselor to the user.")


# Multi-turn adaptive questioner agent conducting cognitive interviews
class QuestionerAgent:
    # Initializes QuestionerAgent, LLM, chains, memory, and output parser
    def __init__(self, llm: Optional[Any] = None, max_turns: int = 5):
        self.llm = llm or get_hf_llm()
        self.max_turns = max_turns
        self.current_turn = 0
        self.current_question: Optional[str] = None
        self.qa_history: Dict[str, str] = {}
        self.memory: List[BaseMessage] = []
        self.parser = PydanticOutputParser(pydantic_object=QuestionMessage)
        self._build_prompts()

    # Builds prompt templates and compiles LCEL chains (prompt | llm | parser)
    def _build_prompts(self):
        format_instructions = self.parser.get_format_instructions()

        self.initial_chat_prompt = PromptTemplate.from_template(
            "You are an expert Counselor Agent evaluating human cognitive and reasoning capabilities.\n"
            "This is Turn 1 of {max_turns}.\n"
            "Task: Generate an engaging, calibrated opening question testing deductive logic, pattern recognition, working memory, or premise validation.\n\n"
            "{format_instructions}\n"
        ).partial(format_instructions=format_instructions)

        self.adaptive_chat_prompt = ChatPromptTemplate.from_messages([
            (
                "system",
                "You are an expert Counselor Agent conducting an adaptive cognitive interview.\n"
                "Current Turn: {turn_index} of {max_turns}.\n"
                "Review the previous questions and answers in conversation memory.\n"
                "Formulate the next evaluation question dynamically adapted to the user's prior reasoning:\n"
                "- Probe depth, test boundary conditions, or pivot to another cognitive dimension.\n"
                "- Do not repeat previous questions.\n\n"
                "{format_instructions}\n"
            ),
            MessagesPlaceholder(variable_name="history"),
            (
                "human",
                "Based on my previous answers in the dialogue history, what is your next evaluation question?",
            ),
        ]).partial(format_instructions=format_instructions)

        self.initial_chain = self.initial_chat_prompt | self.llm | self.parser
        self.adaptive_chain = self.adaptive_chat_prompt | self.llm | self.parser

    # Generates opening question for Turn 1
    def generate_initial_question(self) -> Dict[str, str]:
        result: QuestionMessage = self.initial_chain.invoke({"max_turns": self.max_turns})
        question_text = result.ai.strip()
        self.current_turn = 1
        self.current_question = question_text
        self.memory.append(AIMessage(content=question_text))
        return {"ai": question_text}

    # Generates adaptive follow-up questions
    def generate_next_question(self, interaction: Dict[str, str]) -> Dict[str, str]:
        ai_q = interaction.get("ai") or self.current_question
        user_a = interaction.get("user", "")

        if ai_q:
            self.qa_history[ai_q] = user_a
        self.memory.append(HumanMessage(content=user_a))

        next_turn = self.current_turn + 1
        self.current_turn = next_turn

        result: QuestionMessage = self.adaptive_chain.invoke({
            "turn_index": next_turn,
            "max_turns": self.max_turns,
            "history": self.memory,
        })

        next_question_text = result.ai.strip()
        self.current_question = next_question_text
        self.memory.append(AIMessage(content=next_question_text))
        return {"ai": next_question_text}

    # Returns the accumulated dictionary of questions mapped to user responses
    def get_qa_history(self) -> Dict[str, str]:
        return self.qa_history
