from typing import Dict, List, Optional
from pydantic import BaseModel, Field


class QuestionOutput(BaseModel):
    """Structured question output generated by the Questioner (Counselor) Agent."""

    question: str = Field(
        ...,
        description="The targeted evaluation question to present to the user.",
    )
    dimension_probed: str = Field(
        ...,
        description="The cognitive/reasoning dimension targeted (e.g., deductive_logic, pattern_recognition, working_memory, critical_thinking, premise_validation).",
    )
    difficulty_level: str = Field(
        default="medium",
        description="The difficulty level of the question: 'easy', 'medium', or 'hard'.",
    )
    turn_index: int = Field(
        ...,
        description="The 1-based sequential turn number of this question in the interview.",
    )
    is_evaluation_complete: bool = Field(
        default=False,
        description="Set to True if this interaction reaches the termination threshold and completes the interview.",
    )
    rationale: Optional[str] = Field(
        default=None,
        description="Internal reason why this question was chosen based on prior user responses.",
    )


class FramedInteraction(BaseModel):
    """Structured component produced by the Assistant Agent framing the question and user response."""

    turn_index: int = Field(
        ...,
        description="The turn number of this interaction.",
    )
    question: str = Field(
        ...,
        description="The question that was asked by the Questioner Agent.",
    )
    raw_user_response: str = Field(
        ...,
        description="The verbatim response provided by the user.",
    )
    framed_response: str = Field(
        ...,
        description="Clean, structured framing of the answer highlighting the core reasoning and premises.",
    )
    dimension_probed: str = Field(
        default="general",
        description="The cognitive or reasoning dimension addressed in this interaction.",
    )
    key_observations: Optional[str] = Field(
        default=None,
        description="Brief qualitative observation regarding the user's reasoning style or clarity.",
    )


class QASessionResult(BaseModel):
    """Final output schema encapsulating the complete interview session."""

    total_turns: int = Field(
        ...,
        description="Total number of completed Q&A interactions.",
    )
    qa_pairs: Dict[str, str] = Field(
        ...,
        description="Final mapping where key is the exact question and value is the user's response.",
    )
    structured_interactions: List[FramedInteraction] = Field(
        default_factory=list,
        description="Detailed list of all structured FramedInteraction components.",
    )
